# Generated by Django 5.1.2 on 2024-10-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tarea_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
