# Generated by Django 5.1.2 on 2024-10-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_tarea_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_medicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='medicion_completa',
            field=models.BooleanField(default=False),
        ),
    ]
