# Generated by Django 5.1.2 on 2024-10-31 18:29

import django.contrib.auth.models
import django.db.models.deletion
import django.views.generic.edit
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0005_tarea_fecha_medicion_tarea_medicion_completa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditarTareas',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(django.views.generic.edit.UpdateView, 'auth.user'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
