# Generated by Django 5.1.2 on 2024-11-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_tarea_archivo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='protocolos/'),
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
