# Generated by Django 5.1.2 on 2024-11-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_tarea_archivo_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
