# Generated by Django 5.1.2 on 2024-11-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='descripcion',
            new_name='integrantes',
        ),
        migrations.DeleteModel(
            name='EditarTareas',
        ),
    ]
