# Generated by Django 5.1.2 on 2024-11-29 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_grupotareas_tarea_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='grupo',
        ),
        migrations.AddField(
            model_name='tarea',
            name='anio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.anio'),
        ),
        migrations.AddField(
            model_name='anio',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anios', to='base.grupodetrabajo'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='grupo_de_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.grupodetrabajo'),
        ),
        migrations.DeleteModel(
            name='GrupoTareas',
        ),
    ]
